name: Build Snapshot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar 
  snapshot:
    runs-on: ubuntu-latest
    needs: [build]
    if: success()
    
    steps:
      - name: Get Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d')"
      - name: Print Timestamp
        run: echo ${{steps.timestamp.output.timestamp}}
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: .
      - name: Create release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          prerelease: true
          gzip: false
          tag: snapshot-${{steps.timestamp.output.timestamp}}-${{github.id}}
          files: build-artifacts/*.jar
